#!/bin/bash

BUILD_DIR=.

create-template () {

cat > ${BUILD_DIR}/main.c <<EOF
#include <stdio.h>

#include "printer.h"

int main(int argc, char *argv[]) {
  TYPEA a = NUMA;
  size_t a_size = sizeof(TYPEA);
  TYPEB b = NUMB;
  size_t b_size = sizeof(TYPEB);
  TYPEB c = a OPER b;

  show_all_info("a", (byte_pointer) &a, a_size);
  show_all_info("b", (byte_pointer) &b, b_size);
  show_all_info("a OPER b", (byte_pointer) &c, b_size);

  return 0;
}
EOF

}

pre-process () {

sed -i "s/TYPEA/${TYPEA}/g" ${BUILD_DIR}/main.c
sed -i "s/TYPEB/${TYPEB}/g" ${BUILD_DIR}/main.c
sed -i "s/NUMA/${NUMA}/g" ${BUILD_DIR}/main.c
sed -i "s/NUMB/${NUMB}/g" ${BUILD_DIR}/main.c
sed -i "s/OPER/${OPER}/g" ${BUILD_DIR}/main.c

}

build () {

cd ${BUILD_DIR}

gcc -c printer.c
gcc -c bitviewer.c
gcc -c main.c

gcc printer.o bitviewer.o main.o -o bitviewer

}

clean () {

rm ${BUILD_DIR}/*.o
rm ${BUILD_DIR}/bitviewer
rm ${BUILD_DIR}/main.c

}

run-bitviewer () {

${BUILD_DIR}/bitviewer

}

get-user-input () {

echo "Input a:"
read NUMA

echo

echo "Input b:"
read NUMB

echo

echo "Type a:"
read TYPEA

echo

echo "Type b:"
read TYPEB

echo

echo "Input operation:"
read OPER

echo

export NUMA
export NUMB
export OPER

}

get-user-input

create-template
pre-process

build

run-bitviewer

clean
